#############################################################################
# Makefile for building: meditext
# Generated by qmake (2.01a) (Qt 4.7.4) on: gio nov 24 21:46:56 2011
# Project:  meditext.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile meditext.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = meditext.cpp \
		main.cpp moc_meditext.cpp \
		moc_preferences.cpp \
		qrc_resources.cpp
OBJECTS       = meditext.o \
		main.o \
		moc_meditext.o \
		moc_preferences.o \
		qrc_resources.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		meditext.pro
QMAKE_TARGET  = meditext
DESTDIR       = 
TARGET        = meditext

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_meditext.h ui_preferences.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: meditext.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile meditext.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile meditext.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/meditext1.0.0 || $(MKDIR) .tmp/meditext1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/meditext1.0.0/ && $(COPY_FILE) --parents meditext.h background.h preferences.h document_manager.h .tmp/meditext1.0.0/ && $(COPY_FILE) --parents resources.qrc .tmp/meditext1.0.0/ && $(COPY_FILE) --parents meditext.cpp main.cpp .tmp/meditext1.0.0/ && $(COPY_FILE) --parents meditext.ui preferences.ui .tmp/meditext1.0.0/ && (cd `dirname .tmp/meditext1.0.0` && $(TAR) meditext1.0.0.tar meditext1.0.0 && $(COMPRESS) meditext1.0.0.tar) && $(MOVE) `dirname .tmp/meditext1.0.0`/meditext1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/meditext1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_meditext.cpp moc_preferences.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_meditext.cpp moc_preferences.cpp
moc_meditext.cpp: ui_meditext.h \
		document_manager.h \
		meditext.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) meditext.h -o moc_meditext.cpp

moc_preferences.cpp: ui_preferences.h \
		preferences.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) preferences.h -o moc_preferences.cpp

compiler_rcc_make_all: qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources.cpp
qrc_resources.cpp: resources.qrc \
		icons/new.png \
		icons/icon.png \
		icons/quit.png \
		icons/save.png \
		icons/open.png \
		icons/settings.png
	/usr/bin/rcc -name resources resources.qrc -o qrc_resources.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_meditext.h ui_preferences.h
compiler_uic_clean:
	-$(DEL_FILE) ui_meditext.h ui_preferences.h
ui_meditext.h: meditext.ui
	/usr/bin/uic-qt4 meditext.ui -o ui_meditext.h

ui_preferences.h: preferences.ui
	/usr/bin/uic-qt4 preferences.ui -o ui_preferences.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

meditext.o: meditext.cpp background.cpp \
		background.h \
		preferences.cpp \
		meditext.h \
		ui_meditext.h \
		document_manager.h \
		preferences.h \
		ui_preferences.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o meditext.o meditext.cpp

main.o: main.cpp meditext.h \
		ui_meditext.h \
		document_manager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

moc_meditext.o: moc_meditext.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_meditext.o moc_meditext.cpp

moc_preferences.o: moc_preferences.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_preferences.o moc_preferences.cpp

qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources.o qrc_resources.cpp

####### Install

install_target: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/home/francesco/leziosità/meditext/meditext/ || $(MKDIR) $(INSTALL_ROOT)/home/francesco/leziosità/meditext/meditext/ 
	-$(INSTALL_PROGRAM) "$(QMAKE_TARGET)" "$(INSTALL_ROOT)/home/francesco/leziosità/meditext/meditext/$(QMAKE_TARGET)"
	-$(STRIP) "$(INSTALL_ROOT)/home/francesco/leziosità/meditext/meditext/$(QMAKE_TARGET)"

uninstall_target:  FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/home/francesco/leziosità/meditext/meditext/$(QMAKE_TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/home/francesco/leziosità/meditext/meditext/ 


install_sources: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/home/francesco/leziosità/meditext/./ || $(MKDIR) $(INSTALL_ROOT)/home/francesco/leziosità/meditext/./ 
	-$(INSTALL_FILE) /home/francesco/leziosità/meditext/meditext.cpp $(INSTALL_ROOT)/home/francesco/leziosità/meditext/./
	-$(INSTALL_FILE) /home/francesco/leziosità/meditext/background.cpp $(INSTALL_ROOT)/home/francesco/leziosità/meditext/./
	-$(INSTALL_FILE) /home/francesco/leziosità/meditext/preferences.cpp $(INSTALL_ROOT)/home/francesco/leziosità/meditext/./
	-$(INSTALL_FILE) /home/francesco/leziosità/meditext/main.cpp $(INSTALL_ROOT)/home/francesco/leziosità/meditext/./
	-$(INSTALL_FILE) /home/francesco/leziosità/meditext/meditext.h $(INSTALL_ROOT)/home/francesco/leziosità/meditext/./
	-$(INSTALL_FILE) /home/francesco/leziosità/meditext/background.h $(INSTALL_ROOT)/home/francesco/leziosità/meditext/./
	-$(INSTALL_FILE) /home/francesco/leziosità/meditext/preferences.h $(INSTALL_ROOT)/home/francesco/leziosità/meditext/./
	-$(INSTALL_FILE) /home/francesco/leziosità/meditext/document_manager.h $(INSTALL_ROOT)/home/francesco/leziosità/meditext/./
	-$(INSTALL_FILE) /home/francesco/leziosità/meditext/resources.qrc $(INSTALL_ROOT)/home/francesco/leziosità/meditext/./
	-$(INSTALL_FILE) /home/francesco/leziosità/meditext/meditext.ui $(INSTALL_ROOT)/home/francesco/leziosità/meditext/./
	-$(INSTALL_FILE) /home/francesco/leziosità/meditext/preferences.ui $(INSTALL_ROOT)/home/francesco/leziosità/meditext/./
	-$(INSTALL_FILE) /home/francesco/leziosità/meditext/meditext.pro $(INSTALL_ROOT)/home/francesco/leziosità/meditext/./


uninstall_sources:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/home/francesco/leziosità/meditext/./meditext.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/francesco/leziosità/meditext/./background.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/francesco/leziosità/meditext/./preferences.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/francesco/leziosità/meditext/./main.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/francesco/leziosità/meditext/./meditext.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/francesco/leziosità/meditext/./background.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/francesco/leziosità/meditext/./preferences.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/francesco/leziosità/meditext/./document_manager.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/francesco/leziosità/meditext/./resources.qrc 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/francesco/leziosità/meditext/./meditext.ui 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/francesco/leziosità/meditext/./preferences.ui 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/francesco/leziosità/meditext/./meditext.pro
	-$(DEL_DIR) $(INSTALL_ROOT)/home/francesco/leziosità/meditext/./ 


install:  install_target install_sources  FORCE

uninstall: uninstall_target uninstall_sources   FORCE

FORCE:

